layout_spectrum: 0.8594270245448714
typography_spectrum: 0.8674557678193076
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.6141082562961717
  lightness: 0.5198310458856533
  saturation: 0.17242005056000806
  rhythmicContrast: 0.0036499295383691788
name: howtochristian
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Main Page - How To
    id: 0e5f3f06-167a-4233-8e69-107b208b984a
    type: content
title: HOW DO I?
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/430c6651-d4d6-4abb-a374-142b31ac4665.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/430c6651-d4d6-4abb-a374-142b31ac4665.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/e4154bc9-81ea-41b7-8ef3-29ed457a92de.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/e4154bc9-81ea-41b7-8ef3-29ed457a92de.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  This Site Helps Christians Answer a Whole Lot of Questions on How to do/Become
  What They Desire and What God Desires for Them.
github: true
content_rating:
  adult: false
